server:
  port: 8222
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-customer
          uri: lb:http://MS-CUSTOMER
          predicates:
            - Path=/api/v1/customers/**
        - id: ms-product
          uri: lb:http://MS-PRODUCT
          predicates:
            - Path=/api/v1/products/**
        - id: ms-payment
          uri: lb:http://MS-PAYMENT
          predicates:
            - Path=/api/v1/payments/**
        - id: ms-order
          uri: lb:http://MS-ORDER
          predicates:
            - Path=/api/v1/orders/**
        - id: ms-notification
          uri: lb:http://MS-NOTIFICATION
          predicates:
            - Path=/api/v1/notifications/**
