server:
  port: 8053
spring:
  data:
    mongodb:
      username: cbgomes
      password: cbgomes
      host: localhost
      port: 27017
      database: notifications
      authentication-database: admin
  mail:
    smtp:
      auth: true
      startrls:
        enable: true
      host: mail.viaresults.com.br
      port: 465
    username: carlos@viaresults.com.br
    password: Cax@016803
  kafka:
    consumer:
      group-id: consumer-notifications
