
server:
  port: 8050
spring:
  application:
    name: ms-order
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5533/ms-order
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
ms:
  external:
    config:
      customers-url: http://localhost:8222/api/v1/customers
      products-url: http://localhost:8222/api/v1/products
      payments-url: http://localhost:8222/api/v1/payments
