server:
  port: 8053
spring:
  data:
    mongodb:
      username: cbgomes
      password: cbgomes
      host: localhost
      port: 27017
      database: notifications
      authentication-database: admin
