spring:
  data:
    mongodb:
      username: cbgomes
      password: cbgomes
      host: localhost
      port: 27017
      database: customers
      authentication-database: admin

server:
  port: 8090
  
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
